version: '3.8'

services:
  iot-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///./app/iot.db

  grafana:  # <-- Ahora estÃ¡ bien alineado debajo de iot-app
    image: grafana/grafana:latest
    container_name: grafana-1
    ports:
      - "3000:3000"
    user: "0"  
    environment:
      - GF_PLUGINS_INSTALL=frser-sqlite-datasource
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana_data:/var/lib/grafana 
      - .:/app:ro 

volumes:
  grafana_data: